# relevant docs:
# - http://docs.travis-ci.com/user/languages/groovy/
# - http://blog.freeside.co/2013/02/26/grails-builds-on-travis-ci/

sudo: required

language: groovy

jdk:
  - openjdk8

services: docker

script: ./gradlew build

after_success:
  if [ ! -z "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    docker build -t gkiko/streama:latest -f docker/Dockerfile .;
    docker tag gkiko/streama:latest gkiko/streama:$TRAVIS_TAG;
    docker push gkiko/streama:latest;
    docker push gkiko/streama:$TRAVIS_TAG;
  fi
