# relevant docs:
# - http://docs.travis-ci.com/user/languages/groovy/
# - http://blog.freeside.co/2013/02/26/grails-builds-on-travis-ci/

language: groovy

dist: precise

jdk:
  - oraclejdk8


script: ./gradlew check
