# Place this file next to the streama-[version].war and rename to application.yml with your own settings
environments:
    production:
        dataSource:
#            driverClassName:  'com.mysql.jdbc.Driver'
#            url: jdbc:mysql://localhost/streama
#            username: root
#            password:
            driverClassName:  'org.h2.Driver'
            url: jdbc:h2:./streama;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            username: root
            password:
        server:
            port: 8080

streama:
  regex:
    movies: ^(?<Name>.*)[._ ]\(\d{4}\).*
    shows:
      - ^(?<Name>.+)[._ ][Ss](?<Season>\d{2})[Ee](?<Episode>\d{2,3}).*    # example:  "House.MD.S03E04.h264.mp4"
      - ^(?<Name>.+)[._ ](?<Season>\d{1,2})x(?<Episode>\d{2,3}).*         # example:  "House.MD.03x04.h264.mp4"
      - ^(?<Season>\d{2})-(?<Episode>\d{2,3})-(?<Name>.*?)-.*             # example:  "02-05-Dr. House-Tanz_ums_Feuer-cineonws.mp4"
      - ^(?<Name>.*?)(?<Episode>\d{1,3})x(?<Season>\d{2}).*               # example:  "Castle4x06DaemonsWebdl480pOktober242011rC.mkv(jkuzt).mp4"

